### ISSUE TITLE
Using SSE-S3 Encryption?

### ISSUE THREAD

**Issue by notsoluckycharm** [TTLabs/EvaporateJS#302]
Hello, 

I'm trying to get SSE-S3 encryption working with Evaporate. According to the documentation, the x-amz-server-side​-encryption header should be sent during the [Init phase ](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadInitiate.html) so my code looks like this

```js
        Evaporate.create({
            // TODO dynamic
            bucket: config.videoBucket,
            aws_key: config.awsKey,
            awsRegion: config.awsRegion,
            signerUrl: `${config.getSignedUrl(interview)}`,
            signParams: {
                interview: interview,
                question_id: question.id,
                access_token: getToken()
            }
        }).then( evaporate => {
            evaporate.add({
                name: getVideoPath( interview, question ),
                file: blob,
                xAmzHeadersAtInitiate: {
                    'x-amz-acl': 'public-read',
                    'x-amz-server-side​-encryption': 'AES256',
                    // KMS
                    // 'x-amz-server-side-encryption-aws-kms-key-id' : '',
                    // 'x-amz-server-side-encryption-context': '',

                },
                warn: warn => {
                    console.warn( "warning", warn )
                    // evaporate.pause()
                },
                error: error => {
                    console.error( "error", error )
                    evaporate.pause()
                }
            })
            .then(
                awsKey => {
                    console.log('Completed', awsKey)
                },
                reason => {
                    console.log('Did not upload', reason)
                    evaporate.pause()
                }
            )

        }, function(reason){
            console.log( 'Failed', reason )
        })
```

However I receive the following error:

```
V2 stringToSign: POST



x-amz-acl:public-read
x-amz-date:Thu, 19 Jan 2017 19:56:46 GMT
x-amz-server-side​-encryption:AES256
/on-demand-report-red/UserInterview_291769/162356/162356.mp4?uploads

evaporate.js?e8b4:1167 initiate signature: DdQcjmhtTZipDQ8Owm/dL91jKFU=

evaporate.js?e8b4:1048 initiate error: on-demand-report-red/UserInterview_291769/162356/162356.mp4 DOMException: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'x-amz-server-side​-encryption' is not a valid HTTP header field name.
    at eval (eval at <anonymous> (http://localhost:8000/assets/app.js:6697:2), <anonymous>:1123:15)
    at InitiateMultipartUpload.SignedS3AWSRequest.sendRequestToAWS (eval at <anonymous> (http://localhost:8000/assets/app.js:6697:2), <anonymous>:1087:12)
    at eval (eval at <anonymous> (http://localhost:8000/assets/app.js:6697:2), <anonymous>:1177:20)
```

Has anyone gotten this to work? 

Thanks!

**Comment by notsoluckycharm** [comment]
It's not completely obvious from the various different places you can stumble upon encryption using the amazon docs, but do make sure you've exposed this header in your [CORS policy](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTcors.html). 

The ambiguous error from Chrome's preflight check didn't help.
